[workspace]
members = [
    "aeron-lib",
    "aeron-example", 
]

exclude = [
    "aeron-cpp-archive-client", 
    "aeron-cpp-client",
    "aeron-cpp-wrapper-client",
    "aeron-c-client", 
    "aeron-c-driver", 
]